feat: init gateway
noslate-project/noslate pull request #5
Opened 2022-09-27 09:30 UTC by umuoy1

- Add back-end implementation for gateway
- Add 5 aworker demos，see `gateway/server/functions`

2022-09-27 09:44 UTC, mariodu requested changes

2022-09-27 09:44 UTC, mariodu commented on gateway/server/index.js
> +        await this.agent.setPlatformEnvironmentVariables([{
这个环境变量有用到嘛

2022-09-27 09:44 UTC, mariodu commented on gateway/server/index.js
> +const Logger = require(path.join(PROJECT_DIR, 'lib/logger'));
不要依赖 runtime 里的内容吧，如果要依赖，最好用 NOSLATE_PATH 引入

2022-09-27 09:44 UTC, mariodu commented on gateway/server/index.js
> +const Logger = require(path.join(PROJECT_DIR, 'lib/logger'));
示例和 runtime 解耦，只通过 sdk 连接

2022-09-27 09:45 UTC, mariodu commented on gateway/devstart.js
> +const control = cp.spawn(path.join(__dirname, '../../alice/bin/control_plane'), { stdio: 'pipe', detached: false });
用 NOSLATE_PATH 引入，下面一样

2022-09-27 09:45 UTC, mariodu commented on gateway/server/MOCK_FUNCTION_PROFILE.json
> +    "url": "file:///workspace/dev-size/noslate/noslate/gateway/server/functions/hello-html",
文件路径，要不上传到 OSS 上也可以

2022-09-27 09:46 UTC, mariodu commented on gateway/server/functions/LEB128/index.js
> +        基于 alinode-cloud (serverless worker) 开发
基于 Noslate Workers 开发

2022-09-27 09:47 UTC, legendecas commented on gateway/server/MOCK_FUNCTION_PROFILE.json
> +    "url": "file:///workspace/dev-size/noslate/noslate/gateway/server/functions/hello-html",
不需要 OSS 吧，可以通过 JS 设置 profile 把路径重定位一下就好了。

2022-09-27 09:50 UTC, mariodu requested changes

2022-09-27 09:50 UTC, mariodu commented on gateway/devstart.js
> +process.env.EAGLEEYE_STATLOG_FORCE_STOP = 'true';
EAGLEEYE 去掉

2022-09-27 09:53 UTC, mariodu commented
wormfork 要加个样例吧

2022-09-27 13:13 UTC, umuoy1 commented on gateway/server/MOCK_FUNCTION_PROFILE.json
> +    "url": "file:///workspace/dev-size/noslate/noslate/gateway/server/functions/hello-html",
这里只用文件就好了吧，OSS 后面可以再加 case

2022-09-27 13:16 UTC, umuoy1 commented on gateway/server/index.js
> +        await this.agent.setPlatformEnvironmentVariables([{
@legendecas 这个需要嘛

2022-09-28 06:23 UTC, legendecas commented on gateway/devstart.js
> +process.env.TURF_WORKDIR = path.join(ALICE_WORKDIR, '.turf');
```suggestion
process.env.TURF_WORKDIR = path.join(NOSLATE_WORKDIR, '.turf');
```

2022-09-28 06:23 UTC, legendecas commented on gateway/devstart.js
> +const control = cp.spawn(path.join(ALICE_WORKDIR, 'bin/control_plane'), { stdio: 'pipe', detached: false });
```suggestion
const control = cp.spawn(path.join(NOSLATE_PATH, 'bin/control_plane'), { stdio: 'pipe', detached: false });
```

2022-09-28 09:42 UTC, legendecas commented on gateway/devstart.js
> +process.env.TURF_WORKDIR = path.join(NOSLATE_WORKDIR, '.turf');
这个得删掉吧

2022-09-28 09:42 UTC, legendecas commented on gateway/server/index.js
> +            tmp.forEach(v => {
抽成一个通用的 render 函数？

2022-09-28 10:44 UTC, legendecas approved these changes

2022-09-29 03:13 UTC, merged